### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by itamarst** [tahoe-lafs/zfec#115]
1. Would release the faster builds for x86-64 Linux.
2. Would allow Python 3.13 users to get a binary wheel instead of having to compile it themselves.

**Comment by meejah** [comment]
I am listed as "maintainer" on PyPI but cannot do release stuff (e.g. create a token). So I don't know what "maintainer" actually means there?

**Comment by meejah** [comment]
nevermind, tokens are under "account" not "publishing" I guess ...

**Comment by meejah** [comment]
1.6.0.0 is released

**Comment by itamarst** [comment]
Thank you!
