### ISSUE TITLE
add Python 3.11 support

### ISSUE THREAD

**Issue by MironBodewes** [tahoe-lafs/zfec#74]
It works fine for me with 3.10.6, but with python 3.11 it doesn't install. Edit: see exarkuns comment. I did change the Issue name.

**Comment by exarkun** [comment]
This is expected.  zfec is not yet tested against Python 3.11.  This ticket could be retitled to "add Python 3.11 support" and someone could do the necessary CI setup, fix any issues, and make a release happen.

**Comment by WojciechMigda** [comment]
@MironBodewes It may interest you that `zfex`, a fork of `zfec` which I maintain, builds and installs with cpython 3.11.

**Comment by sajith** [comment]
Did a quick test on macOS (arm64) and Fedora 37 (x86_64). With Python 3.11, `pip install zfec` does install from the sdist package when a C compiler is available, so the issue must be that there are no wheel packages for Python 3.11?

I suppose can can do some things:

- Add Python 3.10 and Python 3.11 to the "test" workflow.
- Update cibuildwheel in the "build" workflow (they're now at 2.x releases, and we're pinned at 1.6.4) and until it magically makes py310 and py311 wheels.  There's also a `pypa/cibuildwheel@version` action now, which simplifies things.

We could also look into abi3 wheels again (#49), now that cibuildwheel has support for it.
